def get_default_arguments():
    return dict(
        data=dict(
            kg_reverse=False,
            kg_export=True,
            hg_LLM_feature_dir=[
                'data/nyc/brand_id2embedding.pkl',
                'data/nyc/category_id2embedding.pkl',
                'data/nyc/junccate_id2embedding.pkl',
                'data/nyc/junction_id2embedding.pkl',
                'data/nyc/poi2embedding.pkl',
                'data/nyc/region_id2embedding.pkl',
                'data/nyc/road_id2embedding.pkl',
                'data/nyc/roadcate_id2embedding.pkl',
            ],
            kg_dir_list=['data/nyc/mht180_prepared.csv', 'data/chi/chi869_prepared.csv'],
            spatial_list=[
                [
                    'data/nyc/region_centroid.csv',
                    'data/nyc/poi_lat_lon.csv'
                ],
                None,
            ],
            image_list=[
                'data/nyc/region_si_img.npy',
                None,
            ],
            flow_list=[
                [
                    'data/nyc/flow_in_per_hour.npy',
                    'data/nyc/flow_out_per_hour.npy',
                    'aug',
                ],
                [
                    'data/chi/flow_in_per_hour_1.npy',
                    'data/chi/flow_out_per_hour_1.npy',
                    'aug',
                ],
            ],
            hg_LLM_feature_dir_list=[
                [
                    'data/nyc/brand_id2embedding.pkl',
                    'data/nyc/category_id2embedding.pkl',
                    'data/nyc/junccate_id2embedding.pkl',
                    'data/nyc/junction_id2embedding.pkl',
                    'data/nyc/poi2embedding.pkl',
                    'data/nyc/region_id2embedding.pkl',
                    'data/nyc/road_id2embedding.pkl',
                    'data/nyc/roadcate_id2embedding.pkl',
                    dict(
                        brand='data/nyc/brand_id2embedding.pkl',
                        category='data/nyc/category_id2embedding.pkl',
                        junccate='data/nyc/junccate_id2embedding.pkl',
                        junction='data/nyc/junction_id2embedding.pkl',
                        poi='data/nyc/poi2embedding.pkl',
                        region='data/nyc/region_id2embedding.pkl',
                        road='data/nyc/road_id2embedding.pkl',
                        roadcate='data/nyc/roadcate_id2embedding.pkl',
                    ),
                ],
                [
                    'data/chi/brand_id2embedding.pkl',
                    'data/chi/category_id2embedding.pkl',
                    'data/chi/junccate_id2embedding.pkl',
                    'data/chi/junction_id2embedding.pkl',
                    'data/chi/poi2embedding.pkl',
                    'data/chi/region_id2embedding.pkl',
                    'data/chi/road_id2embedding.pkl',
                    'data/chi/roadcate_id2embedding.pkl',
                    dict(
                        brand='data/chi/brand_id2embedding.pkl',
                        category='data/chi/category_id2embedding.pkl',
                        junccate='data/chi/junccate_id2embedding.pkl',
                        junction='data/chi/junction_id2embedding.pkl',
                        poi='data/chi/poi2embedding.pkl',
                        region='data/chi/region_id2embedding.pkl',
                        road='data/chi/road_id2embedding.pkl',
                        roadcate='data/chi/roadcate_id2embedding.pkl',
                    ),
                ],
            ],
            mobility_dir=['data/nyc/mobility_distribution.npy', 'data/chi/mobility_distribution_1.npy'],
            flow_dir=[['data/nyc/flow_in_per_hour.npy', 'data/nyc/flow_out_per_hour.npy'],
                      ['data/chi/flow_in_per_hour_1.npy', 'data/chi/flow_out_per_hour_1.npy']],
            coordinator_link_threshold=dict(
                brand=0.1,
                category=0.1,
                junccate=0.1,
                roadcate=0.1,
            ),
            intra_all_region_nearby_list_dir='intra_all_region_nearby_list.joblib',
            intra_all_region_pair_sub_list_dir=None,
            inter_all_region_pair_sub_list_dir=None,
            seed=114514,
        ),
        model=dict(
            seed=114514,
            node_dim=[768, 144, 144],
            edge_dim=32,
            edge_in_dim=32,
            edge_out_dim=32,
            node_dict={'brand': 0, 'cate1': 1, 'junc_cate': 2, 'junction': 3, 'poi': 4, 'region': 5, 'road': 6, 'road_cate': 7},
            edge_dict={'JCateOf': 0, 'BrandOf': 1, 'Cate1Of': 2, 'HasJunc': 3, 'HasPoi': 4, 'HasRoad': 5, 'NearBy': 6,
                       'RCateOf': 7},

            # ['brand', 'cate1', 'junc_cate', 'junction', 'l1_brand', 'l1_cate1', 'l1_junccate', 'l1_roadcate', 'poi', 'region', 'road', 'road_cate', 'schema_brand', 'schema_cate1', 'schema_junc_cate', 'schema_junction', 'schema_poi', 'schema_region', 'schema_road', 'schema_road_cate', 'schema_streetview']
            intra_node_dict={'brand': 0, 'cate1': 1, 'junc_cate': 2, 'junction': 3, 'l1_brand': 4, 'l1_cate1': 5, 'l1_junccate': 6,
                             'l1_roadcate': 7, 'poi': 8, 'region': 9, 'road': 10, 'road_cate': 11, 'schema_brand': 12,
                             'schema_cate1': 13, 'schema_junc_cate': 14, 'schema_junction': 15, 'schema_poi': 16,
                             'schema_region': 17, 'schema_road': 18, 'schema_road_cate': 19, 'schema_streetview': 20},
            # ['JCateOf', 'l1_brand_sim', 'level1to2_Brand', 'l1_cate1_sim', 'level1to2_Cate1', 'l1_junccate_sim', 'level1to2_JuncCate', 'l1_roadcate_sim', 'level1to2_RoadCate', 'BrandOf', 'Cate1Of', 'HasJunc', 'HasPoi', 'HasRoad', 'NearBy', 'RCateOf', 'level0to1_Brand', 'level0to1_Cate1', 'level0to1_JuncCate', 'schema_HasJuncCate', 'schema_HasBrand', 'schema_HasCate1', 'level0to2_Region', 'schema_HasJunction', 'schema_HasPoi', 'schema_HasRoad', 'schema_HasStreetView', 'schema_NearBy', 'schema_HasRoadCate', 'level0to1_RoadCate']
            intra_edge_dict={'JCateOf': 0, 'l1_brand_sim': 1, 'level1to2_Brand': 2, 'l1_cate1_sim': 3, 'level1to2_Cate1': 4, 'l1_junccate_sim': 5,
                             'level1to2_JuncCate': 6, 'l1_roadcate_sim': 7, 'level1to2_RoadCate': 8, 'BrandOf': 9, 'Cate1Of': 10, 'HasJunc': 11,
                             'HasPoi': 12, 'HasRoad': 13, 'NearBy': 14, 'RCateOf': 15, 'level0to1_Brand': 16, 'level0to1_Cate1': 17,
                             'level0to1_JuncCate': 18, 'schema_HasJuncCate': 19, 'schema_HasBrand': 20, 'schema_HasCate1': 21, 'level0to2_Region': 22,
                             'schema_HasJunction': 23, 'schema_HasPoi': 24, 'schema_HasRoad': 25, 'schema_HasStreetView': 26, 'schema_NearBy': 27,
                             'schema_HasRoadCate': 28, 'level0to1_RoadCate': 29},

            inter_node_dict={'brand': 0, 'cate1': 1, 'junc_cate': 2, 'junction': 3, 'l1_brand': 4, 'l1_cate1': 5, 'l1_junccate': 6,
                             'l1_roadcate': 7, 'poi': 8, 'region': 9, 'road': 10, 'road_cate': 11, 'schema_brand': 12,
                             'schema_cate1': 13, 'schema_junc_cate': 14, 'schema_junction': 15, 'schema_poi': 16,
                             'schema_region': 17, 'schema_road': 18, 'schema_road_cate': 19, 'schema_streetview': 20},
            # ['JCateOf', 'cross_city_l1_brand', 'l1_brand_sim', 'level1to2_Brand', 'cross_city_l1_cate1', 'l1_cate1_sim', 'level1to2_Cate1', 'cross_city_l1_junccate', 'l1_junccate_sim', 'level1to2_JuncCate', 'cross_city_l1_roadcate', 'l1_roadcate_sim', 'level1to2_RoadCate', 'BrandOf', 'Cate1Of', 'HasJunc', 'HasPoi', 'HasRoad', 'NearBy', 'RCateOf', 'cross_city_schema_brand', 'level0to1_Brand', 'cross_city_schema_cate1', 'level0to1_Cate1', 'cross_city_schema_junc_cate', 'level0to1_JuncCate', 'schema_HasJuncCate', 'schema_HasBrand', 'schema_HasCate1', 'cross_city_schema_region', 'level0to2_Region', 'schema_HasJunction', 'schema_HasPoi', 'schema_HasRoad', 'schema_HasStreetView', 'schema_NearBy', 'schema_HasRoadCate', 'cross_city_schema_road_cate', 'level0to1_RoadCate']
            inter_edge_dict={'JCateOf': 0, 'cross_city_l1_brand': 1, 'l1_brand_sim': 2, 'level1to2_Brand': 3, 'cross_city_l1_cate1': 4,
                             'l1_cate1_sim': 5, 'level1to2_Cate1': 6, 'cross_city_l1_junccate': 7, 'l1_junccate_sim': 8, 'level1to2_JuncCate': 9,
                             'cross_city_l1_roadcate': 10, 'l1_roadcate_sim': 11, 'level1to2_RoadCate': 12, 'BrandOf': 13, 'Cate1Of': 14,
                             'HasJunc': 15, 'HasPoi': 16, 'HasRoad': 17, 'NearBy': 18, 'RCateOf': 19, 'cross_city_schema_brand': 20,
                             'level0to1_Brand': 21, 'cross_city_schema_cate1': 22, 'level0to1_Cate1': 23, 'cross_city_schema_junc_cate': 24,
                             'level0to1_JuncCate': 25, 'schema_HasJuncCate': 26, 'schema_HasBrand': 27, 'schema_HasCate1': 28,
                             'cross_city_schema_region': 29, 'level0to2_Region': 30, 'schema_HasJunction': 31, 'schema_HasPoi': 32,
                             'schema_HasRoad': 33, 'schema_HasStreetView': 34, 'schema_NearBy': 35, 'schema_HasRoadCate': 36,
                             'cross_city_schema_road_cate': 37, 'level0to1_RoadCate': 38},

            region_node_dict={'brand': 0, 'cate1': 1, 'junc_cate': 2, 'junction': 3, 'poi': 4, 'region': 5, 'road': 6, 'road_cate': 7},
            region_edge_dict={'JCateOf': 0, 'BrandOf': 1, 'Cate1Of': 2, 'HasJunc': 3, 'HasPoi': 4, 'HasRoad': 5, 'NearBy': 6,
                              'RCateOf': 7},

            schema_node_dict={'schema_brand': 0, 'schema_cate1': 1, 'schema_junc_cate': 2, 'schema_junction': 3, 'schema_poi': 4,
                              'schema_region': 5, 'schema_road': 6, 'schema_road_cate': 7, 'schema_streetview': 8,
                              'l1_brand': 9, 'l1_cate1': 10, 'l1_junccate': 11, 'l1_roadcate': 12},
            schema_edge_dict={'l1_brand_sim': 0, 'l1_cate1_sim': 1, 'l1_junccate_sim': 2, 'l1_roadcate_sim': 3, 'schema_HasBrand': 4,
                              'schema_HasCate1': 5, 'schema_HasJuncCate': 6, 'schema_HasJunction': 7, 'schema_HasPoi': 8,
                              'schema_HasRegion': 9, 'schema_HasRoad': 10, 'schema_HasRoadCate': 11, 'schema_HasStreetView': 12,
                              'schema_NearBy': 13},
            n_layers=2,
            n_heads=4,
            intra_batch_size=[180, 869],
            inter_batch_size=[5, 5],
            agg_method='add',
            use_norm=True,
            flow_dim=[144, 144, 144],
            out_dim=144,
        ),
        training=dict(
            seed=114514,
            lr=0.001,
            weight_decay=1e-6,
            intra_batch_size=[180, 869],
            inter_batch_size=[5, 5],
            epochs=10,
            spatial_margin=1.0,
            cross_margin=1.0,
            mobility_loss_weight=1000,
            pred_loss_weight=1,
            cross_loss_weight=0.1,
        ),
        code_test=dict(
            log_folder='experiment/code_test',
            logger_name='code_test',
            log_level='INFO',
        ),
    )
